version: '3.9'
services:
  db:
    image: mysql:9.2.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin556
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin556
      MYSQL_DATABASE: rest_with_spring_boot_matheus
      
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - matheus-network
  rest-with-spring-boot-matheus:
    image: rest-with-spring-boot-matheus
    restart: always
    build: ./
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_matheus?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin556
    ports:
      - 80:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - matheus-network
networks:
  matheus-network:
    driver: bridge

