server:
  port: 80
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://matheus.com.br
file:
  upload-dir: /Projetos/rest-with-spring-boot-and-java/uploadDir
security:
  jwt:
    token:
      security-key: 556bmg0507
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_matheus?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin556
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
springdoc: 
  pathsToMath:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true